#include <iostream>
#include <windows.h>
#include <ctime>
#include <conio.h>
using namespace std;
bool Button;
int insuline = 100;


//this function is used to manually start or stop the program
void Logic(){
	if(_kbhit){
		switch(_getch()){
			case 's':
				Button = false;
				break;			
		}	
	}
	
}

void sugarLevel(){	
	time_t tt; //Declaring arguement for time function
	
	struct tm * ti; //Declaring variable to store the returned value from localtime() function
	
	time(&tt); //This function applies the time 
	
	ti = localtime(&tt); //This function is used to return the system time for log
	
	int randomNumber; // storing the random number generated by rand() API
	srand(time(0));
	randomNumber = rand() % 6; //rand() API only returns between 0 to 5 (the seed might be same for RNG)
	
	int buzzer=7; //using this as an ASCII charecter to trigger the PC speaker, won't work properly on laptops
	
	if(randomNumber<=1){
		
	cout<<"Low blood sugar detected, consume something sweet" << endl;
		printf("%c",buzzer);// this will make an audio alert whenever sugar level is too low. don't know if it's an API call
		
		
	}
	else if (randomNumber == 2){
		cout <<"sugar level is normal" << endl;
		cout << endl;
	}
	else if (randomNumber == 3 ){
		insuline = insuline - 3;
		cout <<"High blood sugar detected, Insoline pump set to active" << endl;
		cout << "Sugar level was at 200 on " << asctime(ti) <<"   3 units of insoline was injected" <<endl;
		cout <<"data recorded to log file \n";
		//we'll make hardwere API calls to run the pump here
		cout << endl;
	}
	else if(randomNumber == 4){
		insuline = insuline - 8;
		cout <<"High blood sugar detected, Insoline pump set to active" << endl;
		cout << "Sugar level was at 300 on " << asctime(ti) << "   8 units insuline was injected " << endl;
		cout <<"data recorded to log file \n";
		cout << endl;
	}
		else if (randomNumber == 5){
			insuline = insuline - 12;
			cout <<"High blood sugar detected, Insoline pump set to active" << endl;
			cout << "Sugar level was at 400 on " << asctime(ti) << "  12 units insuline was injected"<<endl;
			cout <<"data recorded to log file \n";
			cout << endl;		
	}
	
	//The sleep function Slow down our program
	Sleep(5000); //windows API to pause the program for 5 seconds
	
	if(insuline > 0){
		sugarLevel();
	}
	else{
		cout << "Insufficient insuline detected, please refill your insuline pump ";
		printf("%c",buzzer);
		printf("%c",buzzer); //to alert the patient
		printf("%c",buzzer);
		Button = true;
	}
}
int main(int argc, char** argv) {
	cout <<"press 's' to start " << endl;
	cout<<"you can close the window to stop the program"<< endl; //since the trigger to stop the program broke
	cout << endl;
	
	Logic();
	while(!Button){	
		sugarLevel();
		}
	}
